version - 3/Models/Software.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace version_1.Models
{
    public class Software : Asset
    {   
        [Required]
        [RegularExpression(@"^[a-zA-Z]+(([',. -][a-zA-Z ])?[a-zA-Z]*)*$", ErrorMessage = "Enter the valid name")]
        public string SoftwareName { get; set; }

        [Required]
        [RegularExpression(@"^[a-zA-Z]+(([',. -][a-zA-Z ])?[a-zA-Z]*)*$", ErrorMessage = "Enter the valid name")]
        public string SoftwareCompany { get; set; }
    }
}

version - 3/Controllers/SoftwareController.cs
using version_1.Models;
using Microsoft.AspNetCore.Mvc;
using version_1.ViewModels;

namespace version_1.Controllers
{
    public class SoftwareController : Controller
    {
        private readonly ISoftwareRepository _softwareRepository;

        public SoftwareController(ISoftwareRepository softwareRepository)
        {
            _softwareRepository = softwareRepository;
        }

        public IActionResult Details(string softwareName)
        {
            GenericViewModel<Software> genericViewModel = new GenericViewModel<Software>()
            {
                PageTitle = "Software Details"
            };

            if (string.IsNullOrEmpty(softwareName))
            {
                genericViewModel.AssetType = _softwareRepository.GetAllSoftwares();
            }
            else
            {
                genericViewModel.AssetType = _softwareRepository.SearchSoftware(softwareName);
            }

            return View(genericViewModel);
        }

        [HttpGet]
        public ViewResult AddNewSoftware()
        {
            return View();
        }

        [HttpPost]
        public IActionResult AddNewSoftware(Software newSoftware)
        {
            if(ModelState.IsValid)
            {
                _softwareRepository.AddNewSoftware(newSoftware);

                return RedirectToAction("Details");
            }
            
            return View();
        }

        [HttpGet]
        public ViewResult UpdateSoftware(int id)
        {
            Software software = _softwareRepository.GetSoftwareById(id);

            return View(software);
        }

        [HttpPost]
        public IActionResult UpdateSoftware(Software software, int id)
        {
            software.AssetId = id;

            if (ModelState.IsValid)
            {
                _softwareRepository.UpdateSoftware(software);

                return RedirectToAction("Details");
            }

            return View(software);
        }

        public IActionResult Delete(int id)
        {
            _softwareRepository.DeleteSoftware(id);

            return RedirectToAction("Details");
        }
    }
}

version - 3/Views/Software/AddNewSoftware.cshtml
@model Software

<link rel="stylesheet" href="~/css/Software/AddNewSoftware.css">

<div class="container">
    <div class="jumbotron">
        <form class="form" asp-controller="Software" asp-action="AddNewSoftware" method="POST">
            <div class="form-group">
                <label asp-for="SoftwareName">Software Name</label>
                <input type="text" class="form-control" asp-for="SoftwareName" placeholder="Enter Software Name" >
                <span asp-validation-for="SoftwareName" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="SoftwareCompany" >Software Company Name</label>
                <input type="text" class="form-control" asp-for="SoftwareCompany" placeholder="Software Company Name" >
                <span asp-validation-for="SoftwareCompany" class="text-danger"></span>
            </div>
            
            <div class="form-group">
                <label asp-for="AssetPrice" >Software Price $</label>
                <input class="form-control" asp-for="AssetPrice" placeholder="Price" >
                <span asp-validation-for="AssetPrice" class="text-danger"></span>
            </div>
            
            <button type="submit" class="btn btn-primary">Submit</button>
          </form>
    </div>
</div>

version - 3/Views/Software/Details.cshtml
@model GenericViewModel<Software>


<!-- link the style sheet -->
<link rel="stylesheet" href="~/css/Software/software.css">

<!-- main content -->
<div class="container">
    <div class="jumbotron">
        <div class="upperContainer">
            <form asp-controller="Software" asp-action="Details" method="GET">
                <input class="form-control" type="text" name = "softwareName" placeholder="Search Software by Name" aria-label="Search" required>
            </form>
            <a class="btn btn-primary btn-lg add-button" asp-controller="Software" asp-action="AddNewSoftware" >Add New Software</a>
        </div>
        
        <hr>
        

        <div class="row">
            @foreach (var software in @Model.AssetType)
            {
                <div class="software col-lg-4 col-md-4 col-sm-6 col-xs-12">
                    <div class="thumbnail">
                        <img src = "https://images.unsplash.com/photo-1534972195531-d756b9bfa9f2?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60" alt="">
                        <h5>@software.SoftwareName</h5>
                        <p>Price : $@software.AssetPrice</p>
                        <div class="btn-group" role="group" aria-label="Basic example">
                            <a class="btn btn-primary" asp-controller="Software" asp-action="UpdateSoftware" asp-route-Id="@software.AssetId" >Update</a>
                            <form asp-controller="Software" asp-action="Delete" asp-route-id="@software.AssetId" method="POST">
                                <button type="submit" class="btn btn-primary">Delete</button>
                            </form>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>

version - 3/Views/Software/UpdateSoftware.cshtml
@model Software

<link rel="stylesheet" href="~/css/Software/UpdateSoftware.css">

<div class="container">
    <div class="jumbotron">
        <form class="form" asp-controller="Software" asp-action="UpdateSoftware" asp-route-id="@Model.AssetId" method="POST">
            <div class="form-group">
                <label asp-for="SoftwareName" >Software Name</label>
                <input type="text" class="form-control" asp-for="SoftwareName" value="@Model.SoftwareName"  placeholder="Enter Software Name" >
                <span asp-validation-for="SoftwareName"></span>
            </div>

            <div class="form-group">
                <label asp-for="SoftwareCompany" >Software Company Name</label>
                <input type="text" class="form-control" asp-for="SoftwareCompany" value="@Model.SoftwareCompany"  placeholder="Software Company Name" >
                <span asp-validation-for="SoftwareCompany"></span>
            </div>
            
            <div class="form-group">
                <label asp-for="AssetPrice">Software Price $:</label>
                <input class="form-control" asp-for="AssetPrice" value="@Model.AssetPrice" placeholder="Price" >
                <span asp-validation-for="AssetPrice"></span>
            </div>

            <button type="submit" class="btn btn-primary">Submit</button>
          </form>
    </div>
</div>