version - 3/Models/Printer.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace version_1.Models
{
    public class Printer : Hardware
    {   
        [Required]
        [RegularExpression(@"^[a-zA-Z]+(([',. -][a-zA-Z ])?[a-zA-Z]*)*$", ErrorMessage = "Enter the valid name")]
        public string PrinterName { get; set; }

        [Required]
        [RegularExpression(@"^[a-zA-Z]+(([',. -][a-zA-Z ])?[a-zA-Z]*)*$", ErrorMessage = "Enter the valid name")]
        public string CompanyName { get; set; }
        
        [Required]
        [RegularExpression(@"^[a-zA-Z]+(([',. -][a-zA-Z ])?[a-zA-Z]*)*$", ErrorMessage = "Enter the valid name")]
        public string PrinterType { get; set; }
        
        [Required]
        [RegularExpression(@"^[a-zA-Z]+(([',. -][a-zA-Z ])?[a-zA-Z]*)*$", ErrorMessage = "Enter the valid name")]
        public string PrinterQuality { get; set; }
    }
}

version - 3/Controllers/PrinterController.cs
using version_1.Models;
using Microsoft.AspNetCore.Mvc;
using version_1.ViewModels;

namespace version_1.Controllers
{
    public class PrinterController : Controller
    {
        private readonly IPrinterRepository _printerRepository;

        public PrinterController(IPrinterRepository printerRepository)
        {
            _printerRepository = printerRepository;
        }

        public IActionResult Details(string printerName)
        {
            GenericViewModel<Printer> genericViewModel = new GenericViewModel<Printer>()
            {
                PageTitle = "Hardware Details"
            };

            if (string.IsNullOrEmpty(printerName))
            {
                genericViewModel.AssetType = _printerRepository.GetAllPrinters();
            }
            else
            {
                genericViewModel.AssetType = _printerRepository.SearchPrinter(printerName);
            }

            return View(genericViewModel);
        }

        [HttpGet]
        public ViewResult AddNewPrinter()
        {
            return View();
        }

        [HttpPost]
        public IActionResult AddNewPrinter(Printer newPrinter)
        {
            if(ModelState.IsValid)
            {
                _printerRepository.AddNewPrinter(newPrinter);

                return RedirectToAction("Details");
            }
            
            return View();
        }

        [HttpGet]
        public ViewResult UpdatePrinter(int id)
        {
            Printer printer = _printerRepository.GetPrinterById(id);

            return View(printer);
        }

        [HttpPost]
        public IActionResult UpdatePrinter(Printer printer, int id)
        {
            printer.AssetId = id;

            if (ModelState.IsValid)
            {
                _printerRepository.UpdatePrinter(printer);

                return RedirectToAction("Details");
            }

            return View(printer);
        }

        public IActionResult Delete(int id)
        {
            _printerRepository.DeletePrinter(id);

            return RedirectToAction("Details");
        }
    }
}

version - 3/Views/Printer/AddNewPrinter.cshtml
@model Printer

<link rel="stylesheet" href="~/css/Printer/AddNewPrinter.css">

<div class="container">
    <div class="jumbotron">
        <form class="form" asp-controller="Printer" asp-action="AddNewPrinter" method="POST">
            <div class="form-group">
                <label asp-for="PrinterName">Printer Name</label>
                <input type="text" class="form-control" asp-for="PrinterName" placeholder="Enter Printer Name" >
                <span asp-validation-for="PrinterName" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="CompanyName" >Laptop Company Name</label>
                <input type="text" class="form-control" asp-for="CompanyName" placeholder="Printer Company Name" >
                <span asp-validation-for="CompanyName" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="AssetPrice" >Printer Price $</label>
                <input class="form-control" asp-for="AssetPrice" placeholder="Price" >
                <span asp-validation-for="AssetPrice" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="PrinterQuality" >Printer Quality</label>
                <input class="form-control" asp-for="PrinterQuality" placeholder="Enter Printer Quality from Low, Medium or High" >
                <span asp-validation-for="PrinterQuality" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="PrinterType" >Printer Type</label>
                <input class="form-control" asp-for="PrinterType" placeholder="Enter Type Color or Black" >
                <span asp-validation-for="PrinterType" class="text-danger"></span>
            </div>

            <button type="submit" class="btn btn-primary">Submit</button>
          </form>
    </div>
</div>

version - 3/Views/Printer/Details.cshtml
@model GenericViewModel<Printer>


<!-- link the style sheet -->
<link rel="stylesheet" href="~/css/Printer/printer.css">

<!-- main content -->
<div class="container">
    <div class="jumbotron">
        <div class="upperContainer">
            <form asp-controller="Printer" asp-action="Details" method="GET">
                <input class="form-control" type="text" name = "printerName" placeholder="Search printers" aria-label="Search" required>
            </form>
            <a class="btn btn-primary btn-lg add-button" asp-controller="Printer" asp-action="AddNewPrinter" >Add New Printer</a>
        </div>
        
        <hr>
        

        <div class="row">
            @foreach (var printer in @Model.AssetType)
            {
                <div class="printer col-lg-4 col-md-4 col-sm-6 col-xs-12">
                    <div class="thumbnail">
                        <img src = "https://images.unsplash.com/photo-1495046370729-fa5e793723e7?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60" alt="">
                        <h5>@printer.PrinterName</h5>
                        <p>Price : $@printer.AssetPrice</p>
                        <div class="btn-group" role="group" aria-label="Basic example">
                            <a class="btn btn-primary" asp-controller="Printer" asp-action="UpdatePrinter" asp-route-Id="@printer.AssetId" >Update</a>
                            <form asp-controller="Printer" asp-action="Delete" asp-route-id="@printer.AssetId" method="POST">
                                <button type="submit" class="btn btn-primary">Delete</button>
                            </form>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>

version - 3/Views/Printer/UpdatePrinter.cshtml
@model Printer

<link rel="stylesheet" href="~/css/Printer/UpdatePrinter.css">

<div class="container">
    <div class="jumbotron">
        <form class="form" asp-controller="Printer" asp-action="UpdatePrinter" asp-route-id="@Model.AssetId" method="POST">
            <div class="form-group">
                <label asp-for="PrinterName" >Printer Name:</label>
                <input type="text" class="form-control" asp-for="PrinterName" value="@Model.PrinterName"  placeholder="Enter Printer Name" >
                <span asp-validation-for="PrinterName"></span>
            </div>

            <div class="form-group">
                <label asp-for="CompanyName" >Printer Company</label>
                <input type="text" class="form-control" asp-for="CompanyName" value="@Model.CompanyName"  placeholder="Hardware Company Name" >
                <span asp-validation-for="CompanyName"></span>
            </div>

            <div class="form-group">
                <label asp-for="AssetPrice">Laptop Price $:</label>
                <input class="form-control" asp-for="AssetPrice" value="@Model.AssetPrice" placeholder="Price" >
                <span asp-validation-for="AssetPrice"></span>
            </div>

            <div class="form-group">
                <label asp-for="PrinterType">Printer Type</label>
                <input class="form-control" asp-for="PrinterType" value="@Model.PrinterType" placeholder="Printer Type" >
                <span asp-validation-for="PrinterType"></span>
            </div>

            <div class="form-group">
                <label asp-for="PrinterQuality">Printer Quality</label>
                <input class="form-control" asp-for="PrinterQuality" value="@Model.PrinterQuality" placeholder="Enter Printer Quality " >
                <span asp-validation-for="PrinterQuality"></span>
            </div>

            <button type="submit" class="btn btn-primary">Submit</button>
          </form>
    </div>
</div>