version - 3/Models/Laptop.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace version_1.Models
{
    public class Laptop : Hardware
    {   
        [Required]
        [RegularExpression(@"^[a-zA-Z]+(([',. -][a-zA-Z ])?[a-zA-Z]*)*$", ErrorMessage = "Enter the valid name")]
        public string LaptopName { get; set; }
        [Required]
        [RegularExpression(@"^[a-zA-Z]+(([',. -][a-zA-Z ])?[a-zA-Z]*)*$", ErrorMessage = "Enter the valid name")]
        public string CompanyName { get; set; }
        
        [Required]
        public string SerialNumber { get; set; }

        [Required]
        [RegularExpression(@"^[a-zA-Z]+(([',. -][a-zA-Z ])?[a-zA-Z]*)*$", ErrorMessage = "Enter the valid name")]
        public string OperatingSystem { get; set; }
        
        [Required]
        [Range(0, 10, ErrorMessage = "Enter warranty period in range 0 to 10")]
        [RegularExpression(@"^\d{1,1}", ErrorMessage = "Enter valid value")]
        public int WarrantyPeriod { get; set; }
    }
}

version - 3/Controllers/LaptopController.cs
using version_1.Models;
using Microsoft.AspNetCore.Mvc;
using version_1.ViewModels;

namespace version_1.Controllers
{
    public class LaptopController : Controller
    {
        private readonly ILaptopRepository _laptopRepository;

        public LaptopController(ILaptopRepository laptopRepository)
        {
            _laptopRepository = laptopRepository;
        }

        public IActionResult Details(string laptopName)
        {
            GenericViewModel<Laptop> genericViewModel = new GenericViewModel<Laptop>()
            {
                PageTitle = "Hardware Details"
            };

            if (string.IsNullOrEmpty(laptopName))
            {
                genericViewModel.AssetType = _laptopRepository.GetAllLaptops();
            }
            else
            {
                genericViewModel.AssetType = _laptopRepository.SearchLaptop(laptopName);
            }

            return View(genericViewModel);
        }

        [HttpGet]
        public ViewResult AddNewLaptop()
        {
            return View();
        }

        [HttpPost]
        public IActionResult AddNewLaptop(Laptop newLaptop)
        {
            if(ModelState.IsValid)
            {
                _laptopRepository.AddNewLaptop(newLaptop);

                return RedirectToAction("Details");
            }
            
            return View();
        }

        [HttpGet]
        public ViewResult UpdateLaptop(int id)
        {
            Laptop laptop = _laptopRepository.GetLaptopById(id);

            return View(laptop);
        }

        [HttpPost]
        public IActionResult UpdateLaptop(Laptop laptop, int id)
        {
            laptop.AssetId = id;

            if (ModelState.IsValid)
            {
                _laptopRepository.UpdateLaptop(laptop);

                return RedirectToAction("Details");
            }

            return View(laptop);
        }

        public IActionResult Delete(int id)
        {
            _laptopRepository.DeleteLaptop(id);

            return RedirectToAction("Details");
        }
    }
}

version - 3/Views/Laptop/AddNewLaptop.cshtml
@model Laptop

<link rel="stylesheet" href="~/css/Laptop/AddNewLaptop.css">

<div class="container">
    <div class="jumbotron">
        <form class="form" asp-controller="Laptop" asp-action="AddNewLaptop" method="POST">
            <div class="form-group">
                <label asp-for="LaptopName">Laptop Name</label>
                <input type="text" class="form-control" asp-for="LaptopName" placeholder="Enter Laptop Name" >
                <span asp-validation-for="LaptopName" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="CompanyName" >Laptop Company Name</label>
                <input type="text" class="form-control" asp-for="CompanyName" placeholder="Laptop Company Name" >
                <span asp-validation-for="CompanyName" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="AssetPrice" >Laptop Price $</label>
                <input class="form-control" asp-for="AssetPrice" placeholder="Price" >
                <span asp-validation-for="AssetPrice" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="SerialNumber" >Serial Number</label>
                <input class="form-control" asp-for="SerialNumber" placeholder="Enter Serial number" >
                <span asp-validation-for="SerialNumber" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="OperatingSystem" >Operating System</label>
                <input class="form-control" asp-for="OperatingSystem" placeholder="Enter Operating System" >
                <span asp-validation-for="OperatingSystem" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="WarrantyPeriod" >Warranty Period</label>
                <input class="form-control" asp-for="WarrantyPeriod" placeholder="Warranty Period" >
                <span asp-validation-for="WarrantyPeriod" class="text-danger"></span>
            </div>

            <button type="submit" class="btn btn-primary">Submit</button>
          </form>
    </div>
</div>

version - 3/Views/Laptop/Details.cshtml
@model GenericViewModel<Laptop>


<!-- link the style sheet -->
<link rel="stylesheet" href="~/css/Laptop/laptop.css">

<!-- main content -->
<div class="container">
    <div class="jumbotron">
        <div class="upperContainer">
            <form asp-controller="Laptop" asp-action="Details" method="GET">
                <input class="form-control" type="text" name = "laptopName" placeholder="Search laptops" aria-label="Search" required>
            </form>
            <a class="btn btn-primary btn-lg add-button" asp-controller="Laptop" asp-action="AddNewLaptop" >Add New Laptop</a>
        </div>
        
        <hr>
        

        <div class="row">
            @foreach (var laptop in @Model.AssetType)
            {
                <div class="laptop col-lg-4 col-md-4 col-sm-6 col-xs-12">
                    <div class="thumbnail">
                        <img src = "https://images.unsplash.com/photo-1495046370729-fa5e793723e7?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60" alt="">
                        <h5>@laptop.LaptopName</h5>
                        <p>Price : $@laptop.AssetPrice</p>
                        <div class="btn-group" role="group" aria-label="Basic example">
                            <a class="btn btn-primary" asp-controller="Laptop" asp-action="UpdateLaptop" asp-route-Id="@laptop.AssetId" >Update</a>
                            <form asp-controller="Laptop" asp-action="Delete" asp-route-id="@laptop.AssetId" method="POST">
                                <button type="submit" class="btn btn-primary">Delete</button>
                            </form>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>

version - 3/Views/Laptop/UpdateLaptop.cshtml
@model Laptop

<link rel="stylesheet" href="~/css/Laptop/UpdateLaptop.css">

<div class="container">
    <div class="jumbotron">
        <form class="form" asp-controller="Laptop" asp-action="UpdateLaptop" asp-route-id="@Model.AssetId" method="POST">
            <div class="form-group">
                <label asp-for="LaptopName" >Laptop Name:</label>
                <input type="text" class="form-control" asp-for="LaptopName" value="@Model.LaptopName"  placeholder="Enter Laptop Name" >
                <span asp-validation-for="LaptopName"></span>
            </div>

            <div class="form-group">
                <label asp-for="CompanyName" >Laptop Company</label>
                <input type="text" class="form-control" asp-for="CompanyName" value="@Model.CompanyName"  placeholder="Hardware Company Name" >
                <span asp-validation-for="CompanyName"></span>
            </div>

            <div class="form-group">
                <label asp-for="AssetPrice">Laptop Price $:</label>
                <input class="form-control" asp-for="AssetPrice" value="@Model.AssetPrice" placeholder="Price" >
                <span asp-validation-for="AssetPrice"></span>
            </div>

            <div class="form-group">
                <label asp-for="SerialNumber">Serial Number</label>
                <input class="form-control" asp-for="SerialNumber" value="@Model.SerialNumber" placeholder="Serial Number" >
                <span asp-validation-for="SerialNumber"></span>
            </div>

            <div class="form-group">
                <label asp-for="OperatingSystem">Laptop Operating System</label>
                <input class="form-control" asp-for="OperatingSystem" value="@Model.OperatingSystem" placeholder="Enter Operating System Name " >
                <span asp-validation-for="OperatingSystem"></span>
            </div>

            <div class="form-group">
                <label asp-for="WarrantyPeriod">Warranty Period:</label>
                <input class="form-control" asp-for="WarrantyPeriod" value="@Model.WarrantyPeriod" placeholder="Warranty Period" >
                <span asp-validation-for="WarrantyPeriod"></span>
            </div>

            <button type="submit" class="btn btn-primary">Submit</button>
          </form>
    </div>
</div>